symfonycasts_sass:
    root_sass:
        - 'assets/styles/app.scss'
        - 'assets/styles/pages/ishikawa.scss'
        - 'assets/styles/pages/home.scss'
        - 'assets/styles/pages/article-prose.scss'
        - 'assets/styles/pages/five-why.scss'
