symfonycasts_sass:
    root_sass:
        - 'assets/styles/app.scss'
        - 'assets/styles/site/home.scss'
        - 'assets/styles/site/article-prose.scss'
        - 'assets/styles/tools/ishikawa.scss'
        - 'assets/styles/tools/five-why.scss'
