# Désactiver complètement le Web Profiler en production
web_profiler:
    toolbar: false
    intercept_redirects: false

framework:
    profiler:
        collect: false
        only_exceptions: false

